name: Main Flow
on:
  push:
    branches:
      - main

jobs:
  run-pipeline:
    name: Run Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Gradle check
        run:
          ./gradlew check
      - name: Build with Cloud Native Buildpack
        run:
          ./gradlew bootBuildImage --imageName=scorepion --builder heroku/spring-boot-buildpacks
      - name: Tag Docker image
        run:
          docker tag docker.io/library/scorepion:latest registry.heroku.com/scorepion/web
      - name: Login to Heroku Docker Registry
        run:
          docker login --username=${{ secrets.HEROKU_USERNAME }} --password=${{ secrets.HEROKU_API_KEY }} registry.heroku.com
      - name: Push Docker image to Heroku Container Registry
        run:
          docker push registry.heroku.com/scorepion/web
      - name: Update environment variables
        run:
          HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }} heroku config:set ADMIN_USERNAME=${{ secrets.ADMIN_USERNAME }} ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }} DB_PASSWORD=${{ secrets.DB_PASSWORD }} JWT_SECRET=${{ secrets.JWT_SECRET }} -a scorepion
      - name: Redeploy app
        run:
          HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }} heroku container:release web -a scorepion